### PR TITLE
Automated e2e test

### PR DESCRIPTION
**Pull request by zukilover**
Added scenario:
- wargame creation
- forces creation: Red, Blue
- channels creation: All chat, Daily intentions
- umpire interface
- player interfaces

### CODE REVIEW

**Comment by zukilover** [comment]
@IanMayo I have made carefully inspected steps to make sure it doesn't break on most of the times. Network requests are still unreliable especially during first time test run. On the test suites, I targeted these requests by path names, methods, and response statuses. This works just fine for now, but we will need to refactor once the offline mode is up.

**Comment by IanMayo** [comment]
Thanks @zukilover  

CodeFactor has posted some warnings. I presume they're visible to you (maybe they're not :-) ).  Could you resolve them please?

I expect they don't represent actual bugs, but it would be good to work towards zero warnings - so that any new warnings stand out clearly.

**Comment by IanMayo** [comment]
@zukilover - oh, and an unrelated question.  In addition to the test classes, there are quite a few changes to the existing code classes.  Are these changes for:
* extra functionality in order for a test to refer to UI elements
* fixes to problems revealed in testing
* relaxing functionality to make tests pass

**Comment by zukilover** [comment]
> Thanks @zukilover
> 
> CodeFactor has posted some warnings. I presume they're visible to you (maybe they're not :-) ). Could you resolve them please?
> 
> I expect they don't represent actual bugs, but it would be good to work towards zero warnings - so that any new warnings stand out clearly.

Alright sure, I've noticed it just now. I'll work on the fixes soon.

**Comment by zukilover** [comment]
> @zukilover - oh, and an unrelated question. In addition to the test classes, there are quite a few changes to the existing code classes. Are these changes for:
> 
> * extra functionality in order for a test to refer to UI elements
> * fixes to problems revealed in testing
> * relaxing functionality to make tests pass

These changes to the application are mainly for:
- exposing the component's method to the test environment (for example, I need to select the channel tab programmatically, thus I needed to expose `setActiveTab` method)
- putting best practices into test locator (many parts of the components have problematic selectors such as duplicated ids in one page, too many general selectors that are hard to isolate)
- fixing code structures, just to make things tidier.

**Pull request merged**
